export const ADMIN_STATS_REQUEST = "ADMIN_STATS_REQUEST";
export const ADMIN_STATS_SUCCESS = "ADMIN_STATS_SUCCESS";
export const ADMIN_STATS_FAIL = "ADMIN_STATS_FAIL";
export const ADMIN_STATS_RESET = "ADMIN_STATS_RESET";