export const EMAIL_DASHBOARD_ACTIONS = {
  FETCH_REQUEST: "EMAIL_DASHBOARD/FETCH_REQUEST",
  FETCH_SUCCESS: "EMAIL_DASHBOARD/FETCH_SUCCESS",
  FETCH_FAIL: "EMAIL_DASHBOARD/FETCH_FAIL",
  CLEAR_ERROR: "EMAIL_DASHBOARD/CLEAR_ERROR",
};
