export const MANAGE_NEWSLETTER_ACTIONS = {
  ADMIN_LIST_REQUEST: "MANAGE_NEWSLETTER/ADMIN_LIST_REQUEST",
  ADMIN_LIST_SUCCESS: "MANAGE_NEWSLETTER/ADMIN_LIST_SUCCESS",
  ADMIN_LIST_FAIL: "MANAGE_NEWSLETTER/ADMIN_LIST_FAIL",

  ADMIN_UPDATE_REQUEST: "MANAGE_NEWSLETTER/ADMIN_UPDATE_REQUEST",
  ADMIN_UPDATE_SUCCESS: "MANAGE_NEWSLETTER/ADMIN_UPDATE_SUCCESS",
  ADMIN_UPDATE_FAIL: "MANAGE_NEWSLETTER/ADMIN_UPDATE_FAIL",

  ADMIN_DELETE_REQUEST: "MANAGE_NEWSLETTER/ADMIN_DELETE_REQUEST",
  ADMIN_DELETE_SUCCESS: "MANAGE_NEWSLETTER/ADMIN_DELETE_SUCCESS",
  ADMIN_DELETE_FAIL: "MANAGE_NEWSLETTER/ADMIN_DELETE_FAIL",

  SET_SELECTED_ID: "MANAGE_NEWSLETTER/SET_SELECTED_ID",
  SET_SEARCH: "MANAGE_NEWSLETTER/SET_SEARCH",

  SET_SYSTEM_MESSAGE: "MANAGE_NEWSLETTER/SET_SYSTEM_MESSAGE",
  CLEAR_SYSTEM_MESSAGE: "MANAGE_NEWSLETTER/CLEAR_SYSTEM_MESSAGE",
};