// ========== Dashboard Fetch ===============
export const USER_DASHBOARD_REQUEST = "USER_DASHBOARD_REQUEST";
export const USER_DASHBOARD_SUCCESS = "USER_DASHBOARD_SUCCESS";
export const USER_DASHBOARD_FAIL = "USER_DASHBOARD_FAIL";

// ========= UI Toggles / Local UX ==========
export const USER_DASHBOARD_SET_TIME_RANGE = "USER_DASHBOARD_SET_TIME_RANGE";
export const USER_DASHBOARD_MARK_NOTIFICATION_READ =
  "USER_DASHBOARD_MARK_NOTIFICATION_READ";
export const USER_DASHBOARD_CLEAR_ERROR = "USER_DASHBOARD_CLEAR_ERROR";
