export const EMAIL_SEGMENT_ACTIONS = {
  LIST_REQUEST: "EMAIL_SEGMENT/LIST_REQUEST",
  LIST_SUCCESS: "EMAIL_SEGMENT/LIST_SUCCESS",
  LIST_FAIL: "EMAIL_SEGMENT/LIST_FAIL",

  CREATE_REQUEST: "EMAIL_SEGMENT/CREATE_REQUEST",
  CREATE_SUCCESS: "EMAIL_SEGMENT/CREATE_SUCCESS",
  CREATE_FAIL: "EMAIL_SEGMENT/CREATE_FAIL",

  UPDATE_REQUEST: "EMAIL_SEGMENT/UPDATE_REQUEST",
  UPDATE_SUCCESS: "EMAIL_SEGMENT/UPDATE_SUCCESS",
  UPDATE_FAIL: "EMAIL_SEGMENT/UPDATE_FAIL",

  DELETE_REQUEST: "EMAIL_SEGMENT/DELETE_REQUEST",
  DELETE_SUCCESS: "EMAIL_SEGMENT/DELETE_SUCCESS",
  DELETE_FAIL: "EMAIL_SEGMENT/DELETE_FAIL",

  SET_SELECTED: "EMAIL_SEGMENT/SET_SELECTED",
  CLEAR_ERROR: "EMAIL_SEGMENT/CLEAR_ERROR",
  RESET_SUCCESS: "EMAIL_SEGMENT/RESET_SUCCESS",
};