export const NEWSLETTER_ACTIONS = {
  SUBSCRIBE_REQUEST: "NEWSLETTER/SUBSCRIBE_REQUEST",
  SUBSCRIBE_SUCCESS: "NEWSLETTER/SUBSCRIBE_SUCCESS",
  SUBSCRIBE_FAIL: "NEWSLETTER/SUBSCRIBE_FAIL",
  SUBSCRIBE_RESET: "NEWSLETTER/SUBSCRIBE_RESET",
};
