export const MANAGE_REVIEW_REQUEST = "MANAGE_REVIEW_REQUEST";
export const MANAGE_REVIEW_SUCCESS = "MANAGE_REVIEW_SUCCESS";
export const MANAGE_REVIEW_FAIL = "MANAGE_REVIEW_FAIL";

export const MANAGE_REVIEW_APPROVE_SUCCESS =
  "MANAGE_REVIEW_APPROVE_SUCCESS";

export const MANAGE_REVIEW_UNAPPROVE_SUCCESS =
  "MANAGE_REVIEW_UNAPPROVE_SUCCESS";

export const MANAGE_REVIEW_DELETE_SUCCESS =
  "MANAGE_REVIEW_DELETE_SUCCESS";

export const MANAGE_REVIEW_RESET = "MANAGE_REVIEW_RESET";