export const ADMIN_COACHINGS_ACTIONS = {
  HYDRATE_UI: "ADMIN_COACHINGS/HYDRATE_UI",
  SET_UI_FIELD: "ADMIN_COACHINGS/SET_UI_FIELD",

  FETCH_START: "ADMIN_COACHINGS/FETCH_START",
  FETCH_SUCCESS: "ADMIN_COACHINGS/FETCH_SUCCESS",
  FETCH_ERROR: "ADMIN_COACHINGS/FETCH_ERROR",

  UPSERT_ITEM: "ADMIN_COACHINGS/UPSERT_ITEM",
  REMOVE_ITEM: "ADMIN_COACHINGS/REMOVE_ITEM",

  SET_SELECTED_ID: "ADMIN_COACHINGS/SET_SELECTED_ID",
  RESET_STATUS: "ADMIN_COACHINGS/RESET_STATUS",
};