// src/reducers/courseDetail/courseDetailActionTypes.js

export const COURSE_DETAIL_ACTIONS = {
  COURSE_DETAIL_REQUEST: "COURSE_DETAIL_REQUEST",
  COURSE_DETAIL_SUCCESS: "COURSE_DETAIL_SUCCESS",
  COURSE_DETAIL_FAIL: "COURSE_DETAIL_FAIL",

  COURSE_ACCESS_REQUEST: "COURSE_ACCESS_REQUEST",
  COURSE_ACCESS_SUCCESS: "COURSE_ACCESS_SUCCESS",
  COURSE_ACCESS_FAIL: "COURSE_ACCESS_FAIL",

  COURSE_CHECKOUT_REQUEST: "COURSE_CHECKOUT_REQUEST",
  COURSE_CHECKOUT_SUCCESS: "COURSE_CHECKOUT_SUCCESS",
  COURSE_CHECKOUT_FAIL: "COURSE_CHECKOUT_FAIL",

  COURSE_DETAIL_RESET: "COURSE_DETAIL_RESET",
};