// src/reducers/manageUsers/manageUserActionTypes.js

export const MANAGE_USERS_FETCH_START = "MANAGE_USERS_FETCH_START";
export const MANAGE_USERS_FETCH_SUCCESS = "MANAGE_USERS_FETCH_SUCCESS";
export const MANAGE_USERS_FETCH_FAIL = "MANAGE_USERS_FETCH_FAIL";

export const MANAGE_USER_FETCH_START = "MANAGE_USER_FETCH_START";
export const MANAGE_USER_FETCH_SUCCESS = "MANAGE_USER_FETCH_SUCCESS";
export const MANAGE_USER_FETCH_FAIL = "MANAGE_USER_FETCH_FAIL";

export const MANAGE_USER_UPDATE_START = "MANAGE_USER_UPDATE_START";
export const MANAGE_USER_UPDATE_SUCCESS = "MANAGE_USER_UPDATE_SUCCESS";
export const MANAGE_USER_UPDATE_FAIL = "MANAGE_USER_UPDATE_FAIL";

export const MANAGE_USER_STATUS_START = "MANAGE_USER_STATUS_START";
export const MANAGE_USER_STATUS_SUCCESS = "MANAGE_USER_STATUS_SUCCESS";
export const MANAGE_USER_STATUS_FAIL = "MANAGE_USER_STATUS_FAIL";

export const MANAGE_USER_FORCE_LOGOUT_START = "MANAGE_USER_FORCE_LOGOUT_START";
export const MANAGE_USER_FORCE_LOGOUT_SUCCESS =
  "MANAGE_USER_FORCE_LOGOUT_SUCCESS";
export const MANAGE_USER_FORCE_LOGOUT_FAIL = "MANAGE_USER_FORCE_LOGOUT_FAIL";

export const MANAGE_USER_SOFT_DELETE_START = "MANAGE_USER_SOFT_DELETE_START";
export const MANAGE_USER_SOFT_DELETE_SUCCESS =
  "MANAGE_USER_SOFT_DELETE_SUCCESS";
export const MANAGE_USER_SOFT_DELETE_FAIL = "MANAGE_USER_SOFT_DELETE_FAIL";

export const MANAGE_USER_RESTORE_START = "MANAGE_USER_RESTORE_START";
export const MANAGE_USER_RESTORE_SUCCESS = "MANAGE_USER_RESTORE_SUCCESS";
export const MANAGE_USER_RESTORE_FAIL = "MANAGE_USER_RESTORE_FAIL";

export const MANAGE_USER_DELETE_START = "MANAGE_USER_DELETE_START";
export const MANAGE_USER_DELETE_SUCCESS = "MANAGE_USER_DELETE_SUCCESS";
export const MANAGE_USER_DELETE_FAIL = "MANAGE_USER_DELETE_FAIL";

export const MANAGE_USER_SET_SELECTED = "MANAGE_USER_SET_SELECTED";
export const MANAGE_USER_SET_SEARCH = "MANAGE_USER_SET_SEARCH";
export const MANAGE_USER_SET_FILTER = "MANAGE_USER_SET_FILTER";

export const MANAGE_USER_CLEAR_ERROR = "MANAGE_USER_CLEAR_ERROR";
export const MANAGE_USER_RESET = "MANAGE_USER_RESET";
