export const COACHING_ACTIONS = {
  HYDRATE_FROM_STORAGE: "HYDRATE_FROM_STORAGE",
  UPDATE_FIELD: "UPDATE_FIELD",
  SET_STATUS: "SET_STATUS",
  RESET_AFTER_SUCCESS: "RESET_AFTER_SUCCESS",
  RESET_ALL: "RESET_ALL",
};
