export const MANAGE_REVENUE_ACTIONS = {
  FETCH_START: "MANAGE_REVENUE_FETCH_START",
  FETCH_SUCCESS: "MANAGE_REVENUE_FETCH_SUCCESS",
  FETCH_FAILURE: "MANAGE_REVENUE_FETCH_FAILURE",

  SET_SELECTED: "MANAGE_REVENUE_SET_SELECTED",
  CLEAR_SELECTED: "MANAGE_REVENUE_CLEAR_SELECTED",

  UPDATE_FIELD: "MANAGE_REVENUE_UPDATE_FIELD",

  UPDATE_START: "MANAGE_REVENUE_UPDATE_START",
  UPDATE_SUCCESS: "MANAGE_REVENUE_UPDATE_SUCCESS",
  UPDATE_FAILURE: "MANAGE_REVENUE_UPDATE_FAILURE",

  DELETE_START: "MANAGE_REVENUE_DELETE_START",
  DELETE_SUCCESS: "MANAGE_REVENUE_DELETE_SUCCESS",
  DELETE_FAILURE: "MANAGE_REVENUE_DELETE_FAILURE",

  SET_SEARCH: "MANAGE_REVENUE_SET_SEARCH",
  SET_FILTER: "MANAGE_REVENUE_SET_FILTER",
  RESET_ERROR: "MANAGE_REVENUE_RESET_ERROR",
};