// src/reducers/securityEvents/securityEventActionTypes.js

export const SECURITY_EVENT_ACTIONS = {
  FETCH_SECURITY_EVENTS_START: "FETCH_SECURITY_EVENTS_START",
  FETCH_SECURITY_EVENTS_SUCCESS: "FETCH_SECURITY_EVENTS_SUCCESS",
  FETCH_SECURITY_EVENTS_FAIL: "FETCH_SECURITY_EVENTS_FAIL",

  UPDATE_SECURITY_EVENT_REVIEW_START: "UPDATE_SECURITY_EVENT_REVIEW_START",
  UPDATE_SECURITY_EVENT_REVIEW_SUCCESS: "UPDATE_SECURITY_EVENT_REVIEW_SUCCESS",
  UPDATE_SECURITY_EVENT_REVIEW_FAIL: "UPDATE_SECURITY_EVENT_REVIEW_FAIL",

  DELETE_SECURITY_EVENT_START: "DELETE_SECURITY_EVENT_START",
  DELETE_SECURITY_EVENT_SUCCESS: "DELETE_SECURITY_EVENT_SUCCESS",
  DELETE_SECURITY_EVENT_FAIL: "DELETE_SECURITY_EVENT_FAIL",

  DEACTIVATE_SECURITY_EVENT_USER_START:
    "DEACTIVATE_SECURITY_EVENT_USER_START",
  DEACTIVATE_SECURITY_EVENT_USER_SUCCESS:
    "DEACTIVATE_SECURITY_EVENT_USER_SUCCESS",
  DEACTIVATE_SECURITY_EVENT_USER_FAIL:
    "DEACTIVATE_SECURITY_EVENT_USER_FAIL",

  BLOCK_SECURITY_EVENT_IP_START: "BLOCK_SECURITY_EVENT_IP_START",
  BLOCK_SECURITY_EVENT_IP_SUCCESS: "BLOCK_SECURITY_EVENT_IP_SUCCESS",
  BLOCK_SECURITY_EVENT_IP_FAIL: "BLOCK_SECURITY_EVENT_IP_FAIL",

  UNBLOCK_SECURITY_EVENT_IP_START: "UNBLOCK_SECURITY_EVENT_IP_START",
UNBLOCK_SECURITY_EVENT_IP_SUCCESS: "UNBLOCK_SECURITY_EVENT_IP_SUCCESS",
UNBLOCK_SECURITY_EVENT_IP_FAIL: "UNBLOCK_SECURITY_EVENT_IP_FAIL",

  CLEANUP_SECURITY_EVENTS_START: "CLEANUP_SECURITY_EVENTS_START",
  CLEANUP_SECURITY_EVENTS_SUCCESS: "CLEANUP_SECURITY_EVENTS_SUCCESS",
  CLEANUP_SECURITY_EVENTS_FAIL: "CLEANUP_SECURITY_EVENTS_FAIL",

  SET_SECURITY_EVENT_FILTERS: "SET_SECURITY_EVENT_FILTERS",
  CLEAR_SECURITY_EVENT_ERROR: "CLEAR_SECURITY_EVENT_ERROR",
  RESET_SECURITY_EVENTS: "RESET_SECURITY_EVENTS",
};