// src/reducers/manageContact/manageContactActionTypes.js
export const MANAGE_CONTACTS_ACTIONS = {
  FETCH_START: "FETCH_START",
  FETCH_SUCCESS: "FETCH_SUCCESS",
  FETCH_FAIL: "FETCH_FAIL",

  SELECT: "SELECT",
  UPDATE_FIELD: "UPDATE_FIELD",
  CLEAR_ERROR: "CLEAR_ERROR",

  SAVE_START: "SAVE_START",
  SAVE_SUCCESS: "SAVE_SUCCESS",
  SAVE_FAIL: "SAVE_FAIL",

  DELETE_START: "DELETE_START",
  DELETE_SUCCESS: "DELETE_SUCCESS",
  DELETE_FAIL: "DELETE_FAIL",

  BULK_START: "BULK_START",
  BULK_SUCCESS: "BULK_SUCCESS",
  BULK_FAIL: "BULK_FAIL",

  // ✅ NEW: reply thread
  REPLY_START: "REPLY_START",
  REPLY_SUCCESS: "REPLY_SUCCESS",
  REPLY_FAIL: "REPLY_FAIL",

  UPDATE_REPLY_DRAFT: "UPDATE_REPLY_DRAFT",
  CLEAR_REPLY_DRAFT: "CLEAR_REPLY_DRAFT",
};
