export const SYSTEM_SETTING_ACTIONS = {
  SYSTEM_STATUS_REQUEST: "SYSTEM_STATUS_REQUEST",
  SYSTEM_STATUS_SUCCESS: "SYSTEM_STATUS_SUCCESS",
  SYSTEM_STATUS_FAIL: "SYSTEM_STATUS_FAIL",

  UPDATE_MAINTENANCE_REQUEST: "UPDATE_MAINTENANCE_REQUEST",
  UPDATE_MAINTENANCE_SUCCESS: "UPDATE_MAINTENANCE_SUCCESS",
  UPDATE_MAINTENANCE_FAIL: "UPDATE_MAINTENANCE_FAIL",

  SYSTEM_MAINTENANCE_SOCKET_UPDATE: "SYSTEM_MAINTENANCE_SOCKET_UPDATE",

  CLEAR_SYSTEM_SETTING_MESSAGES: "CLEAR_SYSTEM_SETTING_MESSAGES",
};