export const REGISTER_ACTIONS = {
  UPDATE_FIELD: "REGISTER_UPDATE_FIELD",
  SET_ERROR: "REGISTER_SET_ERROR",
  CLEAR_ERROR: "REGISTER_CLEAR_ERROR",
  REQUEST: "REGISTER_REQUEST",
  SUCCESS: "REGISTER_SUCCESS",
  FAIL: "REGISTER_FAIL",
  RESET: "REGISTER_RESET",
};
