// src/reducers/contact/contactActionTypes.js

export const CONTACT_ACTIONS = {
  HYDRATE_FROM_STORAGE: "CONTACT/HYDRATE_FROM_STORAGE",

  UPDATE_FIELD: "CONTACT/UPDATE_FIELD",

  SET_STATUS: "CONTACT/SET_STATUS",
  CLEAR_STATUS: "CONTACT/CLEAR_STATUS",

  RESET_AFTER_SUCCESS: "CONTACT/RESET_AFTER_SUCCESS",

  RESET_FORM: "CONTACT/RESET_FORM",

  RESET_ALL: "CONTACT/RESET_ALL",
};