export const MANAGE_TESTIMONIAL_REQUEST = "MANAGE_TESTIMONIAL_REQUEST";
export const MANAGE_TESTIMONIAL_SUCCESS = "MANAGE_TESTIMONIAL_SUCCESS";
export const MANAGE_TESTIMONIAL_FAIL = "MANAGE_TESTIMONIAL_FAIL";

export const MANAGE_TESTIMONIAL_ACTION_REQUEST =
  "MANAGE_TESTIMONIAL_ACTION_REQUEST";

export const MANAGE_TESTIMONIAL_ACTION_FINISH =
  "MANAGE_TESTIMONIAL_ACTION_FINISH";

export const UPDATE_TESTIMONIAL_SUCCESS = "UPDATE_TESTIMONIAL_SUCCESS";
export const DELETE_TESTIMONIAL_SUCCESS = "DELETE_TESTIMONIAL_SUCCESS";

export const CLEAR_MANAGE_TESTIMONIAL_ERROR =
  "CLEAR_MANAGE_TESTIMONIAL_ERROR";