export const MY_COURSES_ACTIONS = {
  FETCH_MY_COURSES_REQUEST: "FETCH_MY_COURSES_REQUEST",
  FETCH_MY_COURSES_SUCCESS: "FETCH_MY_COURSES_SUCCESS",
  FETCH_MY_COURSES_FAIL: "FETCH_MY_COURSES_FAIL",
  RESET_MY_COURSES: "RESET_MY_COURSES",
};
