export const EMAIL_CAMPAIGN_ACTIONS = {
  LIST_REQUEST: "EMAIL_CAMPAIGN/LIST_REQUEST",
  LIST_SUCCESS: "EMAIL_CAMPAIGN/LIST_SUCCESS",
  LIST_FAIL: "EMAIL_CAMPAIGN/LIST_FAIL",

  CREATE_REQUEST: "EMAIL_CAMPAIGN/CREATE_REQUEST",
  CREATE_SUCCESS: "EMAIL_CAMPAIGN/CREATE_SUCCESS",
  CREATE_FAIL: "EMAIL_CAMPAIGN/CREATE_FAIL",

  UPDATE_REQUEST: "EMAIL_CAMPAIGN/UPDATE_REQUEST",
  UPDATE_SUCCESS: "EMAIL_CAMPAIGN/UPDATE_SUCCESS",
  UPDATE_FAIL: "EMAIL_CAMPAIGN/UPDATE_FAIL",

  DELETE_REQUEST: "EMAIL_CAMPAIGN/DELETE_REQUEST",
  DELETE_SUCCESS: "EMAIL_CAMPAIGN/DELETE_SUCCESS",
  DELETE_FAIL: "EMAIL_CAMPAIGN/DELETE_FAIL",

  SEND_REQUEST: "EMAIL_CAMPAIGN/SEND_REQUEST",
  SEND_SUCCESS: "EMAIL_CAMPAIGN/SEND_SUCCESS",
  SEND_FAIL: "EMAIL_CAMPAIGN/SEND_FAIL",

  ANALYTICS_REQUEST: "EMAIL_CAMPAIGN/ANALYTICS_REQUEST",
  ANALYTICS_SUCCESS: "EMAIL_CAMPAIGN/ANALYTICS_SUCCESS",
  ANALYTICS_FAIL: "EMAIL_CAMPAIGN/ANALYTICS_FAIL",

  SET_SELECTED: "EMAIL_CAMPAIGN/SET_SELECTED",
  CLEAR_ERROR: "EMAIL_CAMPAIGN/CLEAR_ERROR",
  RESET_SUCCESS: "EMAIL_CAMPAIGN/RESET_SUCCESS",
};
