// src/reducers/testimonial/testimonialActionTypes.js

export const TESTIMONIAL_FETCH_START = "TESTIMONIAL_FETCH_START";
export const TESTIMONIAL_FETCH_SUCCESS = "TESTIMONIAL_FETCH_SUCCESS";
export const TESTIMONIAL_FETCH_FAIL = "TESTIMONIAL_FETCH_FAIL";

export const TESTIMONIAL_CLEAR_ERROR = "TESTIMONIAL_CLEAR_ERROR";