export const MANAGE_MEMBERSHIPS_ACTIONS = {
  FETCH_REQUEST: "MANAGE_MEMBERSHIPS_FETCH_REQUEST",
  FETCH_SUCCESS: "MANAGE_MEMBERSHIPS_FETCH_SUCCESS",
  FETCH_FAIL: "MANAGE_MEMBERSHIPS_FETCH_FAIL",

  CREATE_REQUEST: "MANAGE_MEMBERSHIPS_CREATE_REQUEST",
  CREATE_SUCCESS: "MANAGE_MEMBERSHIPS_CREATE_SUCCESS",
  CREATE_FAIL: "MANAGE_MEMBERSHIPS_CREATE_FAIL",

  UPDATE_REQUEST: "MANAGE_MEMBERSHIPS_UPDATE_REQUEST",
  UPDATE_SUCCESS: "MANAGE_MEMBERSHIPS_UPDATE_SUCCESS",
  UPDATE_FAIL: "MANAGE_MEMBERSHIPS_UPDATE_FAIL",

  DELETE_REQUEST: "MANAGE_MEMBERSHIPS_DELETE_REQUEST",
  DELETE_SUCCESS: "MANAGE_MEMBERSHIPS_DELETE_SUCCESS",
  DELETE_FAIL: "MANAGE_MEMBERSHIPS_DELETE_FAIL",

  SET_SELECTED_MEMBERSHIP: "MANAGE_MEMBERSHIPS_SET_SELECTED_MEMBERSHIP",
  CLEAR_SELECTED_MEMBERSHIP: "MANAGE_MEMBERSHIPS_CLEAR_SELECTED_MEMBERSHIP",

  SET_SEARCH: "MANAGE_MEMBERSHIPS_SET_SEARCH",
  SET_LEVEL_FILTER: "MANAGE_MEMBERSHIPS_SET_LEVEL_FILTER",
  SET_STATUS_FILTER: "MANAGE_MEMBERSHIPS_SET_STATUS_FILTER",

  CLEAR_ERROR: "MANAGE_MEMBERSHIPS_CLEAR_ERROR",
  RESET: "MANAGE_MEMBERSHIPS_RESET",
};
