export const MEMBERSHIP_ACTIONS = {
  FETCH_START: "MEMBERSHIP_FETCH_START",
  FETCH_SUCCESS: "MEMBERSHIP_FETCH_SUCCESS",
  FETCH_ERROR: "MEMBERSHIP_FETCH_ERROR",

  START_CHECKOUT: "MEMBERSHIP_START_CHECKOUT",
  STOP_CHECKOUT: "MEMBERSHIP_STOP_CHECKOUT",
  
  CLEAR_ERROR: "MEMBERSHIP_CLEAR_ERROR",
}