export const MEMBERSHIP_ACTIONS = {
  FETCH_START: "MEMBERSHIP_FETCH_START",
  FETCH_SUCCESS: "MEMBERSHIP_FETCH_SUCCESS",
  FETCH_ERROR: "MEMBERSHIP_FETCH_ERROR",

  FETCH_MY_SUBSCRIPTION_START: "MEMBERSHIP_FETCH_MY_SUBSCRIPTION_START",
  FETCH_MY_SUBSCRIPTION_SUCCESS: "MEMBERSHIP_FETCH_MY_SUBSCRIPTION_SUCCESS",
  FETCH_MY_SUBSCRIPTION_ERROR: "MEMBERSHIP_FETCH_MY_SUBSCRIPTION_ERROR",

  START_CHECKOUT: "MEMBERSHIP_START_CHECKOUT",
  STOP_CHECKOUT: "MEMBERSHIP_STOP_CHECKOUT",

  START_SWITCH: "MEMBERSHIP_START_SWITCH",
  STOP_SWITCH: "MEMBERSHIP_STOP_SWITCH",

  START_CANCEL: "MEMBERSHIP_START_CANCEL",
  STOP_CANCEL: "MEMBERSHIP_STOP_CANCEL",

  CLEAR_ERROR: "MEMBERSHIP_CLEAR_ERROR",
};