// src/admin/reducers/manageCourses/manageCoursesActionTypes.js

export const MANAGE_COURSES_ACTIONS = {
  FETCH_START: "MANAGE_COURSES/FETCH_START",
  FETCH_SUCCESS: "MANAGE_COURSES/FETCH_SUCCESS",
  FETCH_FAIL: "MANAGE_COURSES/FETCH_FAIL",

  SAVE_START: "MANAGE_COURSES/SAVE_START",
  CREATE_SUCCESS: "MANAGE_COURSES/CREATE_SUCCESS",
  UPDATE_SUCCESS: "MANAGE_COURSES/UPDATE_SUCCESS",
  SAVE_FAIL: "MANAGE_COURSES/SAVE_FAIL",

  DELETE_START: "MANAGE_COURSES/DELETE_START",
  DELETE_SUCCESS: "MANAGE_COURSES/DELETE_SUCCESS",
  DELETE_FAIL: "MANAGE_COURSES/DELETE_FAIL",

  SET_SELECTED_COURSE: "MANAGE_COURSES/SET_SELECTED_COURSE",
  CLEAR_SELECTED_COURSE: "MANAGE_COURSES/CLEAR_SELECTED_COURSE",

  SET_SEARCH: "MANAGE_COURSES/SET_SEARCH",
  SET_LEVEL_FILTER: "MANAGE_COURSES/SET_LEVEL_FILTER",
  SET_STATUS_FILTER: "MANAGE_COURSES/SET_STATUS_FILTER",

  CLEAR_ERROR: "MANAGE_COURSES/CLEAR_ERROR",
  CLEAR_SUCCESS: "MANAGE_COURSES/CLEAR_SUCCESS",
};