// src/reducers/manageLesson/manageLessonActionTypes.js

export const MANAGE_LESSON_ACTIONS = {
  // Fetch
  LESSONS_REQUEST: "LESSONS_REQUEST",
  LESSONS_SUCCESS: "LESSONS_SUCCESS",
  LESSONS_FAIL: "LESSONS_FAIL",

  // Create
  CREATE_LESSON_REQUEST: "CREATE_LESSON_REQUEST",
  CREATE_LESSON_SUCCESS: "CREATE_LESSON_SUCCESS",
  CREATE_LESSON_FAIL: "CREATE_LESSON_FAIL",

  // Update
  UPDATE_LESSON_REQUEST: "UPDATE_LESSON_REQUEST",
  UPDATE_LESSON_SUCCESS: "UPDATE_LESSON_SUCCESS",
  UPDATE_LESSON_FAIL: "UPDATE_LESSON_FAIL",

  // Delete
  DELETE_LESSON_REQUEST: "DELETE_LESSON_REQUEST",
  DELETE_LESSON_SUCCESS: "DELETE_LESSON_SUCCESS",
  DELETE_LESSON_FAIL: "DELETE_LESSON_FAIL",

  // Reset
  CLEAR_LESSON_MESSAGES: "CLEAR_LESSON_MESSAGES",
};