// src/reducers/manageLesson/manageLessonActionTypes.js

export const MANAGE_LESSON_ACTIONS = {
  // Fetch
  LESSONS_REQUEST: "manageLesson/LESSONS_REQUEST",
  LESSONS_SUCCESS: "manageLesson/LESSONS_SUCCESS",
  LESSONS_FAIL: "manageLesson/LESSONS_FAIL",

  // Create
  CREATE_LESSON_REQUEST: "manageLesson/CREATE_LESSON_REQUEST",
  CREATE_LESSON_SUCCESS: "manageLesson/CREATE_LESSON_SUCCESS",
  CREATE_LESSON_FAIL: "manageLesson/CREATE_LESSON_FAIL",

  // Update
  UPDATE_LESSON_REQUEST: "manageLesson/UPDATE_LESSON_REQUEST",
  UPDATE_LESSON_SUCCESS: "manageLesson/UPDATE_LESSON_SUCCESS",
  UPDATE_LESSON_FAIL: "manageLesson/UPDATE_LESSON_FAIL",

  // Delete
  DELETE_LESSON_REQUEST: "manageLesson/DELETE_LESSON_REQUEST",
  DELETE_LESSON_SUCCESS: "manageLesson/DELETE_LESSON_SUCCESS",
  DELETE_LESSON_FAIL: "manageLesson/DELETE_LESSON_FAIL",

  // UI / Reset
  CLEAR_LESSON_MESSAGES: "manageLesson/CLEAR_LESSON_MESSAGES",
  RESET_LESSON_STATE: "manageLesson/RESET_LESSON_STATE",
};
