// src/redux/user/userActionTypes.js
export const USER_ME_REQUEST = "USER_ME_REQUEST";
export const USER_ME_SUCCESS = "USER_ME_SUCCESS";
export const USER_ME_FAIL = "USER_ME_FAIL";

export const USER_ME_SET_EDIT_MODE = "USER_ME_SET_EDIT_MODE";
export const USER_ME_FORM_UPDATE = "USER_ME_FORM_UPDATE";
export const USER_ME_FORM_RESET = "USER_ME_FORM_RESET";

export const USER_ME_SAVE_REQUEST = "USER_ME_SAVE_REQUEST";
export const USER_ME_SAVE_SUCCESS = "USER_ME_SAVE_SUCCESS";
export const USER_ME_SAVE_FAIL = "USER_ME_SAVE_FAIL";

export const USER_AVATAR_SET_FILE = "USER_AVATAR_SET_FILE";
export const USER_AVATAR_CLEAR = "USER_AVATAR_CLEAR";

export const USER_PASSWORD_PANEL_TOGGLE = "USER_PASSWORD_PANEL_TOGGLE";
export const USER_PASSWORD_UPDATE_FIELD = "USER_PASSWORD_UPDATE_FIELD";
export const USER_PASSWORD_RESET = "USER_PASSWORD_RESET";

export const USER_LOGOUT = "USER_LOGOUT";


