export const EMAIL_SUBSCRIBER_ACTIONS = {
  LIST_REQUEST: "EMAIL_SUBSCRIBER_LIST_REQUEST",
  LIST_SUCCESS: "EMAIL_SUBSCRIBER_LIST_SUCCESS",
  LIST_FAIL: "EMAIL_SUBSCRIBER_LIST_FAIL",

  DETAILS_REQUEST: "EMAIL_SUBSCRIBER_DETAILS_REQUEST",
  DETAILS_SUCCESS: "EMAIL_SUBSCRIBER_DETAILS_SUCCESS",
  DETAILS_FAIL: "EMAIL_SUBSCRIBER_DETAILS_FAIL",

  CREATE_REQUEST: "EMAIL_SUBSCRIBER_CREATE_REQUEST",
  CREATE_SUCCESS: "EMAIL_SUBSCRIBER_CREATE_SUCCESS",
  CREATE_FAIL: "EMAIL_SUBSCRIBER_CREATE_FAIL",

  UPDATE_REQUEST: "EMAIL_SUBSCRIBER_UPDATE_REQUEST",
  UPDATE_SUCCESS: "EMAIL_SUBSCRIBER_UPDATE_SUCCESS",
  UPDATE_FAIL: "EMAIL_SUBSCRIBER_UPDATE_FAIL",

  DELETE_REQUEST: "EMAIL_SUBSCRIBER_DELETE_REQUEST",
  DELETE_SUCCESS: "EMAIL_SUBSCRIBER_DELETE_SUCCESS",
  DELETE_FAIL: "EMAIL_SUBSCRIBER_DELETE_FAIL",

  BULK_STATUS_REQUEST: "EMAIL_SUBSCRIBER_BULK_STATUS_REQUEST",
  BULK_STATUS_SUCCESS: "EMAIL_SUBSCRIBER_BULK_STATUS_SUCCESS",
  BULK_STATUS_FAIL: "EMAIL_SUBSCRIBER_BULK_STATUS_FAIL",

  BULK_DELETE_REQUEST: "EMAIL_SUBSCRIBER_BULK_DELETE_REQUEST",
  BULK_DELETE_SUCCESS: "EMAIL_SUBSCRIBER_BULK_DELETE_SUCCESS",
  BULK_DELETE_FAIL: "EMAIL_SUBSCRIBER_BULK_DELETE_FAIL",

  SET_SELECTED: "EMAIL_SUBSCRIBER_SET_SELECTED",
  CLEAR_SELECTED: "EMAIL_SUBSCRIBER_CLEAR_SELECTED",

  SET_SEARCH: "EMAIL_SUBSCRIBER_SET_SEARCH",
  SET_FILTER: "EMAIL_SUBSCRIBER_SET_FILTER",
  SET_SORT: "EMAIL_SUBSCRIBER_SET_SORT",

  CLEAR_ERROR: "EMAIL_SUBSCRIBER_CLEAR_ERROR",
  RESET_SUCCESS: "EMAIL_SUBSCRIBER_RESET_SUCCESS",
};