export const EMAIL_SUBSCRIBER_ACTIONS = {
  LIST_REQUEST: "EMAIL_SUBSCRIBER/LIST_REQUEST",
  LIST_SUCCESS: "EMAIL_SUBSCRIBER/LIST_SUCCESS",
  LIST_FAIL: "EMAIL_SUBSCRIBER/LIST_FAIL",

  UPDATE_REQUEST: "EMAIL_SUBSCRIBER/UPDATE_REQUEST",
  UPDATE_SUCCESS: "EMAIL_SUBSCRIBER/UPDATE_SUCCESS",
  UPDATE_FAIL: "EMAIL_SUBSCRIBER/UPDATE_FAIL",

  DELETE_REQUEST: "EMAIL_SUBSCRIBER/DELETE_REQUEST",
  DELETE_SUCCESS: "EMAIL_SUBSCRIBER/DELETE_SUCCESS",
  DELETE_FAIL: "EMAIL_SUBSCRIBER/DELETE_FAIL",

  SET_SELECTED_SUBSCRIBER: "EMAIL_SUBSCRIBER/SET_SELECTED_SUBSCRIBER",
  CLEAR_SELECTED_SUBSCRIBER: "EMAIL_SUBSCRIBER/CLEAR_SELECTED_SUBSCRIBER",

  SET_SEARCH: "EMAIL_SUBSCRIBER/SET_SEARCH",
  SET_FILTER: "EMAIL_SUBSCRIBER/SET_FILTER",

  CLEAR_ERROR: "EMAIL_SUBSCRIBER/CLEAR_ERROR",
  RESET_SUCCESS: "EMAIL_SUBSCRIBER/RESET_SUCCESS",
};