// src/reducers/myCourseDetail/myCourseDetailActionTypes.js

export const MY_COURSE_DETAIL_ACTIONS = {
  MY_COURSE_DETAIL_REQUEST: "MY_COURSE_DETAIL_REQUEST",
  MY_COURSE_DETAIL_SUCCESS: "MY_COURSE_DETAIL_SUCCESS",
  MY_COURSE_DETAIL_FAIL: "MY_COURSE_DETAIL_FAIL",

  MY_COURSE_LESSONS_REQUEST: "MY_COURSE_LESSONS_REQUEST",
  MY_COURSE_LESSONS_SUCCESS: "MY_COURSE_LESSONS_SUCCESS",
  MY_COURSE_LESSONS_FAIL: "MY_COURSE_LESSONS_FAIL",

  MY_COURSE_DETAIL_RESET: "MY_COURSE_DETAIL_RESET",
};
