export const EMAIL_ANALYTICS_ACTIONS = {
  FETCH_REQUEST: "EMAIL_ANALYTICS/FETCH_REQUEST",
  FETCH_SUCCESS: "EMAIL_ANALYTICS/FETCH_SUCCESS",
  FETCH_FAIL: "EMAIL_ANALYTICS/FETCH_FAIL",
  CLEAR_ERROR: "EMAIL_ANALYTICS/CLEAR_ERROR",
};