// src/reducers/manageOrders/manageOrderActionTypes.js

// 🏆 MANAGE ORDERS ACTION TYPES
// Premium admin order management system:
// fetch, edit, update, delete, fulfill, cancel, refund, and save orders safely.

export const MANAGE_ORDER_ACTIONS = {
  FETCH_START: "MANAGE_ORDERS/FETCH_START",
  FETCH_SUCCESS: "MANAGE_ORDERS/FETCH_SUCCESS",
  FETCH_FAILURE: "MANAGE_ORDERS/FETCH_FAILURE",

  SET_SELECTED_ORDER: "MANAGE_ORDERS/SET_SELECTED_ORDER",
  CLEAR_SELECTED_ORDER: "MANAGE_ORDERS/CLEAR_SELECTED_ORDER",

  SET_EDIT_ORDER: "MANAGE_ORDERS/SET_EDIT_ORDER",
  UPDATE_EDIT_FIELD: "MANAGE_ORDERS/UPDATE_EDIT_FIELD",
  CLEAR_EDIT_ORDER: "MANAGE_ORDERS/CLEAR_EDIT_ORDER",

  UPDATE_START: "MANAGE_ORDERS/UPDATE_START",
  UPDATE_SUCCESS: "MANAGE_ORDERS/UPDATE_SUCCESS",
  UPDATE_FAILURE: "MANAGE_ORDERS/UPDATE_FAILURE",

  DELETE_START: "MANAGE_ORDERS/DELETE_START",
  DELETE_SUCCESS: "MANAGE_ORDERS/DELETE_SUCCESS",
  DELETE_FAILURE: "MANAGE_ORDERS/DELETE_FAILURE",

  SET_FILTER: "MANAGE_ORDERS/SET_FILTER",
  SET_SEARCH: "MANAGE_ORDERS/SET_SEARCH",
  SET_SORT: "MANAGE_ORDERS/SET_SORT",

  RESET_ERROR: "MANAGE_ORDERS/RESET_ERROR",
};