export const ENROLLMENT_FETCH_MY_REQUEST = "ENROLLMENT_FETCH_MY_REQUEST";
export const ENROLLMENT_FETCH_MY_SUCCESS = "ENROLLMENT_FETCH_MY_SUCCESS";
export const ENROLLMENT_FETCH_MY_FAIL = "ENROLLMENT_FETCH_MY_FAIL";
export const ENROLLMENT_CLEAR_ERROR = "ENROLLMENT_CLEAR_ERROR";
