export const MY_PRODUCTS_REQUEST = "MY_PRODUCTS_REQUEST";
export const MY_PRODUCTS_SUCCESS = "MY_PRODUCTS_SUCCESS";
export const MY_PRODUCTS_FAIL = "MY_PRODUCTS_FAIL";
export const MY_PRODUCTS_CLEAR_ERROR = "MY_PRODUCTS_CLEAR_ERROR";
