export const EMAIL_TEMPLATE_ACTIONS = {
  LIST_REQUEST: "EMAIL_TEMPLATE/LIST_REQUEST",
  LIST_SUCCESS: "EMAIL_TEMPLATE/LIST_SUCCESS",
  LIST_FAIL: "EMAIL_TEMPLATE/LIST_FAIL",

  CREATE_REQUEST: "EMAIL_TEMPLATE/CREATE_REQUEST",
  CREATE_SUCCESS: "EMAIL_TEMPLATE/CREATE_SUCCESS",
  CREATE_FAIL: "EMAIL_TEMPLATE/CREATE_FAIL",

  UPDATE_REQUEST: "EMAIL_TEMPLATE/UPDATE_REQUEST",
  UPDATE_SUCCESS: "EMAIL_TEMPLATE/UPDATE_SUCCESS",
  UPDATE_FAIL: "EMAIL_TEMPLATE/UPDATE_FAIL",

  DELETE_REQUEST: "EMAIL_TEMPLATE/DELETE_REQUEST",
  DELETE_SUCCESS: "EMAIL_TEMPLATE/DELETE_SUCCESS",
  DELETE_FAIL: "EMAIL_TEMPLATE/DELETE_FAIL",

  SET_SELECTED: "EMAIL_TEMPLATE/SET_SELECTED",
  CLEAR_ERROR: "EMAIL_TEMPLATE/CLEAR_ERROR",
  RESET_SUCCESS: "EMAIL_TEMPLATE/RESET_SUCCESS",
};